language: go

go:
  - "1.11.x"

env:
  global:
    - GIT_DEPLOY_DIR=out
    - GIT_DEPLOY_BRANCH=master
    - GIT_DEPLOY_USERNAME="Travis CI" # dummy name
    - GIT_DEPLOY_EMAIL=hejtmy@gmail.com # replace by your email
    - HUGO_VERSION=0.80.0

branches:
  only:
    - release

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.deb -O /tmp/hugo.deb && sudo dpkg -i /tmp/hugo.deb
  - rm -rf ../${GIT_DEPLOY_DIR} || exit 0 # cleanup previous run

script:
  - git submodule update --init
  - git submodule update --remote --merge
  - hugo -d ../${GIT_DEPLOY_DIR}
  - 'if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo "https://www.hejtmy.com" > ../${GIT_DEPLOY_DIR}/CNAME; fi'

deploy:
  provider: pages
  skip_cleanup: true
  target-branch: ${GIT_DEPLOY_BRANCH}
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: ../${GIT_DEPLOY_DIR}
  on:
    branch: release
