baseurl = "http://hejtmy.com"
title = "hejtmy"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Lukáš Hejtmánek"
    info = "PhD in Neuroscience, master's in psychology, data scientist, videogaming & boardgaming geek, VR enthusiast"
    description = "Lukáš Hejtmánek's personal website"
    keywords = "blog, developer, personal"
    avatarurl = ""

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = ""

    hidecredits = false
    hidecopyright = false
    rtl = false
    math = true
    custom_css = ["css/custom.css"]


# Social links
[[params.social]]
    name = "Github"
    icon = "fa fa-github fa-2x"
    weight = 1
    url = "https://github.com/hejtmy/"
[[params.social]]
    name = "email"
    icon = "fa fa-envelope fa-2x"
    weight = 3
    url = "mailto:hejtmy@gmail.com"
[[params.social]]
    name = "Google scholar"
    icon = "fas fa-book-open fa-2x"
    weight = 3
    url = "https://scholar.google.com/citations?user=bXK961cAAAAJ&hl=en"
[[params.social]]
    name = "ResearchGate"
    icon = "fab fa-researchgate fa-2x"
    weight = 3
    url = "https://www.researchgate.net/profile/Lukas_Hejtmanek"
[[params.social]]
    name = "Linkedin"
    icon = "fa fa-linkedin fa-2x"
    weight = 3
    url = "https://www.linkedin.com/in/lukashejtmanek/"
[[params.social]]
    name = "Twitter"
    icon = "fa fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/hejtmy_"


# Menu links
[[menu.main]]
    name = "Publications"
    weight = 1
    url = "/publications/"
[[menu.main]]
    name = "Packages"
    weight = 3
    url = "/packages/"
[[menu.main]]
  name = "CV"
  weight= 4
  url="/files/cv-hejtmanek.pdf"
#[[menu.main]]
#    name = "Projects"
#    weight = 2
#    url = "/projects/"
[[menu.main]]
    name = "Blog"
    weight = 5
    url  = "http://www.neuro-coder.com"
[[menu.main]]
    name = "About"
    weight = 10
    url = "/about/"
